---
- name: Install system required packages
  ansible.builtin.package:
    name:
      - wget
      - git
      - curl
      - gcc
      - findutils
      - make
      - rsync
      - tar
      - lz4
    state: present
