---
# Configure a chain node
- name: Configure a chain node
  hosts: node
  roles:
    - {role: create_user, become: true }
    - {role: add_dependencies, become: true }
    - {role: build_ipfs}
    - {role: service, become: true }
